### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [ivadimko/template-jwood#1]
1. Откуда на всех section этот `class="_mPS2id-t"`
1. Подумай с нулевым экраном, тут или media (max-height: ** ) и что то с ним интересное делать или установить для него минимальную высоту.
1. Добавь плавности элементам при `:hover`
1. _Mail, Phone, Social Media_ не заголовки

**Comment by vadim-ilchenko** [comment]
> *Откуда на всех section этот class="_mPS2id-t"*

Из за плагина плавного скролла. Magic Page Scroll to ID.

> *Подумай с нулевым экраном, тут или media (max-height: .. ) и что то с ним интересное делать или установить для него минимальную высоту*

На каких размерах баг виден? Я хромом не могу увидеть, чтобы он поехал. Да и на телефоне у меня отображается адекватно (за исключением строки URL, которая сдвигает экран вниз на телефоне).

> *Добавь плавности элементам при :hover*

Тут понятно

> *Mail, Phone, Social Media не заголовки*

И тут понятно)

**Comment by vadim-ilchenko** [comment]
[**FIXED**](https://ivadimko.github.io/template-jwood/)
