### ISSUE TITLE
Баги 2.0

### ISSUE THREAD

**Issue by yuchiko** [ivadimko/template-jwood#2]
1. Не хватает отступа http://joxi.ru/MAjpx91f43zeVm
2. При :hover сдвиг иконки http://joxi.ru/gmv759qsLG5k12
3. Сгруппировал бы их
```
    footer .content .mail a {
        font-size: 20px
    }

    footer .content .phone a {
        font-size: 20px
    }
```

Заголовки 👍 
Bootstap breakpoint 👍

**Comment by vadim-ilchenko** [comment]
1. Добавил http://joxi.ru/Rmz1jdkuWdgB9r
2. Переделал :hover
3. Теперь так 
`footer .content .mail a, footer .content .phone a {
    font-size: 20px;
}`

[RESULT](https://ivadimko.github.io/template-jwood/)
